---
development:
  adapter: async
production:
  adapter: solid_cable
  connects_to:
    database:
      writing: cable
  message_retention: 1.day
  polling_interval: 0.1.seconds
test:
  adapter: test
