service: vincent
image: dorianmariecom/vincent
servers:
  web:
    - 138.201.175.197
proxy:
  ssl: true
  host: vincent.dorianmarie.com
registry:
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - RAILS_MASTER_KEY
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
volumes:
  - "vincent_storage:/rails/storage"
builder:
  arch: amd64
